// src/services/uploader.ts — bc-resilience-service
import { Octokit }   from '@octokit/rest'
import { readFile }  from 'node:fs/promises'
import { basename }  from 'node:path'

export interface UploadOptions {
  repo:          string
  pdfPath:       string
  markdownPath:  string
  appName:       string
  callerToken:   string
  releaseSuffix: string
}

export async function uploadArtifact(opts: UploadOptions): Promise<string> {
  const { repo, pdfPath, markdownPath, appName, callerToken, releaseSuffix } = opts
  const [owner, repoName] = repo.split('/')
  const octokit = new Octokit({ auth: callerToken })

  const tag = `${releaseSuffix}-${Date.now()}`

  const { data: release } = await octokit.repos.createRelease({
    owner,
    repo:      repoName,
    tag_name:  tag,
    name:      `${appName} Resilience Report — ${new Date().toISOString().slice(0, 10)}`,
    body:      'Generated by @bc-resilience',
    draft:     false,
    prerelease: false,
  })

  const uploadAsset = async (filePath: string, contentType: string) => {
    const data = await readFile(filePath)
    await octokit.repos.uploadReleaseAsset({
      owner,
      repo:     repoName,
      release_id: release.id,
      name:     basename(filePath),
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      data:     data as any,
      headers:  { 'content-type': contentType, 'content-length': data.length },
    })
  }

  await uploadAsset(pdfPath,      'application/pdf')
  await uploadAsset(markdownPath, 'text/markdown')

  return release.html_url
}
