# gitops/argocd/bc-resilience-service-test.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:      bc-resilience-service-test
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name:       bc-resilience-service
    app.kubernetes.io/managed-by: argocd
    environment:                  test
spec:
  project: default
  source:
    repoURL:        https://github.com/rloisell/bc-resilience-service-gitops.git
    targetRevision: test
    path:           charts/bc-resilience
    helm:
      valueFiles:
        - values.yaml
        - values-test.yaml
  destination:
    server:    https://kubernetes.default.svc
    namespace: be808f-test
  syncPolicy:
    automated:
      prune:    true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
